"""empty message

Revision ID: 9077e9f94ec2
Revises: a2ab68cf9283
Create Date: 2021-04-06 04:35:46.737529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9077e9f94ec2'
down_revision = 'a2ab68cf9283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('mass', sa.String(length=50), nullable=True),
    sa.Column('skin_color', sa.String(length=50), nullable=True),
    sa.Column('hair_color', sa.String(length=50), nullable=True),
    sa.Column('eye_color', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('photoUrl', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('population', sa.String(length=50), nullable=True),
    sa.Column('terrain', sa.String(length=50), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('gravity', sa.String(length=50), nullable=True),
    sa.Column('eye_color', sa.String(length=50), nullable=True),
    sa.Column('surface_water', sa.String(length=50), nullable=True),
    sa.Column('orbital_period', sa.String(length=50), nullable=True),
    sa.Column('photoUrl', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favoritos', sa.Column('characters_id', sa.Integer(), nullable=True))
    op.add_column('favoritos', sa.Column('id_tipo', sa.Integer(), nullable=True))
    op.add_column('favoritos', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.add_column('favoritos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('nombre', table_name='favoritos')
    op.create_foreign_key(None, 'favoritos', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favoritos', 'planets', ['planets_id'], ['id'])
    op.create_foreign_key(None, 'favoritos', 'characters', ['characters_id'], ['id'])
    op.add_column('user', sa.Column('fullName', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullName')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.create_index('nombre', 'favoritos', ['nombre'], unique=True)
    op.drop_column('favoritos', 'user_id')
    op.drop_column('favoritos', 'planets_id')
    op.drop_column('favoritos', 'id_tipo')
    op.drop_column('favoritos', 'characters_id')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
