"""empty message

Revision ID: bb67308c8633
Revises: d4756f9ac326
Create Date: 2021-04-12 05:09:26.029668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb67308c8633'
down_revision = 'd4756f9ac326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('galaxy', sa.String(length=50), nullable=True))
    op.drop_column('planets', 'eye_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('eye_color', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('planets', 'galaxy')
    # ### end Alembic commands ###
